name: Deploy Laravel Project on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@master
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
      - name: Install Dependencies
        run: composer install
      - name: Generate key
        run: php artisan key:generate
      - name: Generate storage link
        run: php artisan storage:link
      - name: Database Migration
         run: php artisan migrate
      - name: Database Seeder
         run: php artisan db:seed
      - name: Optimize Clear
         run: php artisan optimize:clear
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:     
          php-version: '8.3'
          extensions: imagick, swoole   
          server: FTP_HOST
          username: FTP_USERNAME
          password: FTP_PASSWORD
